# Generated by Django 5.0.2 on 2024-05-07 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adviser',
            fields=[
                ('uid', models.UUIDField(primary_key=True, serialize=False, verbose_name='ID руководителя')),
                ('first_name', models.CharField(max_length=256, verbose_name='Имя руководителя')),
                ('last_name', models.CharField(max_length=256, verbose_name='Фамилия руководителя')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('uid', models.UUIDField(primary_key=True, serialize=False, verbose_name='ID студента')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя студента')),
                ('last_name', models.CharField(max_length=256, verbose_name='Фамилия студента')),
            ],
        ),
        migrations.CreateModel(
            name='CourseWork',
            fields=[
                ('uid', models.UUIDField(primary_key=True, serialize=False, verbose_name='ID курса')),
                ('name', models.CharField(max_length=256, verbose_name='Тема курсовой работы')),
                ('description', models.TextField(verbose_name='Описание курсовой работы')),
                ('adviser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.adviser', verbose_name='Руководитель')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.student', verbose_name='Исполнитель')),
            ],
            options={
                'verbose_name': 'Курсовая работа',
                'verbose_name_plural': 'Курсовые работы',
            },
        ),
    ]
